"""empty message

Revision ID: 25b0ade915bb
Revises: 42ce0c16dde1
Create Date: 2020-12-09 07:53:01.420810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b0ade915bb'
down_revision = '42ce0c16dde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meme', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meme', type_='unique')
    # ### end Alembic commands ###
