"""empty message

Revision ID: 42ce0c16dde1
Revises: f268f63c3c70
Create Date: 2020-12-09 04:08:02.188449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce0c16dde1'
down_revision = 'f268f63c3c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meme', 'user', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meme', type_='foreignkey')
    op.drop_column('meme', 'likes')
    # ### end Alembic commands ###
