"""empty message

Revision ID: f268f63c3c70
Revises: 8c1def666672
Create Date: 2020-12-05 02:31:35.448671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f268f63c3c70'
down_revision = '8c1def666672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meme', 'user', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meme', type_='foreignkey')
    op.drop_column('meme', 'uploader_id')
    # ### end Alembic commands ###
